### ISSUE TITLE
CustomField - tracking changes

### ISSUE THREAD

**Issue by syampillai** [vaadin/vaadin-custom-field-flow#13]
In the CustomField constructor, we have:
`getElement().addEventListener("change", e -> this.updateValue())`
This means that any change that occurs at the client side will fire `updateValue()` but if there is a "Value Change Listener", the event received by it will NOT show it as coming from the client (see the `false` value passed to `setModelValue` in `updateValue()`. Is this a bug?

I feel that the correct constructor should contain:
`getElement().addEventListener("change", e -> setModelValue(this.generateModelValue(), true)`

**Comment by tulioag** [comment]
Thanks for reporting this issue. I have changed `updateValue` to 
```java
getElement().addEventListener("change", e -> setModelValue(this.generateModelValue(), true)
```
Now it correctly shows as from client. I think this is the solution that will bring the least impact to existing users. If you need to generate an event with `fromClient` as `false` you can always create a different method that calls `setModelValue`
