### ISSUE TITLE
Width of CustomFields in FormLayout

### ISSUE THREAD

**Issue by JohannesLaidler** [vaadin/vaadin-custom-field-flow#18]
**Description of the bug:**

`CustomField`'s width is different from other components in a `FormLayout`.

**Minimal reproducible example:**
```
@Route("test")
public class VaadinTest extends VerticalLayout {

    public VaadinTest() {
        Binder<Bean> binder = new Binder<>();

        TextField nameField = new TextField("Name");
        binder.bind(nameField, Bean::getName, Bean::setName);

        AddressField addressField = new AddressField();
        binder.bind(addressField, Bean::getAddress, Bean::setAddress);

        FormLayout formLayout = new FormLayout(nameField, addressField);
        formLayout.setResponsiveSteps(new ResponsiveStep("0", 1));

        add(formLayout);
    }

    private class AddressField extends CustomField<Address> {

        private TextField cityField = new TextField("City");
        private TextField streetField = new TextField("Street");

        public AddressField() {
            setSizeFull();
            FormLayout formLayout = new FormLayout(cityField, streetField);
            formLayout.setSizeFull();
            add(formLayout);
        }

        @Override
        protected Address generateModelValue() {
            Address address = new Address();
            address.setCity(cityField.getValue());
            address.setStreet(streetField.getValue());
            return address;
        }

        @Override
        protected void setPresentationValue(Address newPresentationValue) {
            if (newPresentationValue != null) {
                cityField.setValue(newPresentationValue.getCity());
                streetField.setValue(newPresentationValue.getStreet());
            }
        }

    }

    private class Bean {
        private String name;
        private Address address;

        public Address getAddress() {
            return address;
        }

        public void setAddress(Address address) {
            this.address = address;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    private class Address {
        private String city;
        private String street;

        public String getCity() {
            return city;
        }

        public void setCity(String city) {
            this.city = city;
        }

        public String getStreet() {
            return street;
        }

        public void setStreet(String street) {
            this.street = street;
        }
    }
}
``` 
**Expected behavior**
Width of `CustomField` should be 100% like other fields in `FormLayout`.
![excpected](https://user-images.githubusercontent.com/45820614/55625353-c869a600-57a8-11e9-9d93-c3205d5212d5.png)
**Actual behavior**
A `Div` in `shadow-root` of `<vaadin-custom-fields>` prevents the `FormLayout` inside the `CustomField` from expanding correctly.
![actual](https://user-images.githubusercontent.com/45820614/55625485-3dd57680-57a9-11e9-81d1-2439f1ac9b45.png)
![div](https://user-images.githubusercontent.com/45820614/55625491-4332c100-57a9-11e9-9c2c-d3e6ae5993a4.gif)
**Versions:**
    - Vaadin / Flow version 13.0.1
    - Java version jdk-11.0.2
    - OS version Windows 10
    - Browser version Google Chrome Version 73.0.3683.103 (64-Bit) / Mozilla Quantum 66.0.2 (64-Bit)

**Comment by tulioag** [comment]
Thanks for reporting this. Since it seems the issue is related to the webcomponent, I have opened a new issue in https://github.com/vaadin/vaadin-custom-field/issues/28

**Comment by syampillai** [comment]
CustomFields are used by me in many places in FormLayout and in most of the places, I need the embedded components within the CustomField should be expanded to 100%. However, it is not needed in some cases. So, I feel that, while fixing this issue, a method to set the content width would be great - something like expandContentFull() or setContentWidth(...).
