### ISSUE TITLE
Cannot read property focus of undefined

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/vaadin-custom-field-flow#40]
I created a CustomCheckbox, when I clicked on the custom field label, I've got this error:
TypeError: Cannot read property 'focus' of undefined

Apparently in vaadin-custom-field.js: inputs is empty
  focus() {
    this.inputs && this.inputs[0].focus();
  }

Here a use case to reproduce this problem:
```
public static class CustomCheckbox
            extends CustomField<Boolean> {

        private final Checkbox checkbox = new Checkbox();

        CustomCheckbox() {
            setLabel("checkbox");
            add(checkbox);
        }

        @Override
        protected Boolean generateModelValue() {
            return checkbox.getValue();
        }

        @Override
        protected void setPresentationValue(
                Boolean newPresentationValue) {
            checkbox.setValue(newPresentationValue);

        }

    }
```

I can reproduce it in Chrome, FF and Safari. But I'm not sure if it's related to vaadin-custom-field or vaadin-custom-field-flow.

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/vaadin-custom-field/pull/58 and released as 3.0.3.
