### ISSUE TITLE
Missing @HtmlImport annotation on CustomField class in Vaadin 14.3.0

### ISSUE THREAD

**Issue by kalmancsaba** [vaadin/vaadin-custom-field-flow#75]
Vaadin 14 is said to fully support bower compatibility mode throughout its whole lifetime.

Vaadin 14.3.0 uses vaadin-custom-field-flow-4.1.0 and in this version, the CustomField class is missing the necessary @HtmlImport annotation, so the webcomponent won't load in compatibility mode.

Please put back the @HtmlImport annotation in Vaadin 14.

**Comment by alvarezguille** [comment]
Thanks for reporting this.
The version for vaadin-custom-field-flow should be 3.1.0, a fix is in progress and will be included in vaadin 14.3.1. In the meantime you can override vaadin-custom-field-flow version to get the proper HTMLImport.

**Comment by kalmancsaba** [comment]
Thank you for the quick response!

**Comment by alvarezguille** [comment]
Fix was included in 14.3.1. Closing the issue.
