### ISSUE TITLE
Add documentation how to use updateValue()

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-custom-field-flow#8]
Add documentation in which cases the automagic internal value change mechanism works and when you need to manually call `updateValue()`.

By automagic internal value changes I mean that this event listener:
```java
    public CustomField(T defaultValue) {
        super(defaultValue);
        // Force a value update when the change event generated
        getElement().addEventListener("change", e -> this.updateValue());
    }
```
will be fired whenever a nested field changes value and bubbles up or something like that.

But if there is a server-side value change listener on the nested fields `updateValue()` needs to be called manually.

**Comment by Peppe** [comment]
Can we get server side to be equally automagic?

**Comment by tulioag** [comment]
The idea is that `updateValue` should not be needed for normal usage. Right now the implementation relies on the change event sent by the client side, but it is not being generated always, as discussed here https://github.com/vaadin/vaadin-custom-field/issues/22#issuecomment-466025457

> But if there is a server-side value change listener on the nested fields updateValue() needs to be called manually.

It seems that this is another case where it doesn't work. It should not be needed.

**Comment by tulioag** [comment]
Documentation has been updated. Please reopen or create a new issue if it still seems unclear.
